In [3]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

> List_ is a python list object and

> array_list is a numpy array.

In [11]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


-------------

### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list. 

In [18]:
# For List
l = [(type(i)) for i in list_]
l

[str, str, str, str, str]

In [20]:
# For array_list
a = [ i.dtype for i in np.nditer(array_list)]
a

[dtype('<U1'), dtype('<U1'), dtype('<U1'), dtype('<U1'), dtype('<U1')]

--------------

### Q3. Considering the following changes in the variable, array_list:

     array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [21]:
array_list = np.array(object = list_, dtype = int)
array_list

array([1, 2, 3, 4, 5])

>> array_list is numpy object which values are converted in Integer Format

In [25]:
# For List
l = [(type(i)) for i in list_]
al = [ i.dtype for i in np.nditer(array_list)]
print('list Type :', l, '\n' 'array_list  :', al)

list Type : [<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>] 
array_list  : [dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64')]


---------------

### Q4. Write a code to find the following characteristics of variable, num_array:
    -(i) shape
    -(ii) size

In [26]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [27]:
print('for Shape :', num_array.shape, '\n''for Size :', num_array.size)

for Shape : (2, 3) 
for Size : 6


_______

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [30]:
import numpy.matlib as nm
nm.zeros((2,3))

matrix([[0., 0., 0.],
        [0., 0., 0.]])

_______

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [56]:
ar = nm.eye(5)

In [57]:
ar

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

___________